### ISSUE TITLE
Add chrome to or_else (line 39 - version 0.1.1 )

### ISSUE THREAD

**Issue by felipetesc** [JAD3N/browsers#2]
As always, Windows executable name differs. Inside the method get_browser_path, 
I added or_else method and now the path to Chrome can be found on Windows:

it was (line 39): 
```rust 
   BrowserKind::Chrome => which("google-chrome").or_else(|_| which("google-chrome-stable")),
```

And it is: 

```rust
   BrowserKind::Chrome => which("google-chrome").or_else(|_| which("google-chrome-stable").or_else(|_|which("chrome"))),
}
```
TY

**Comment by JAD3N** [comment]
I daily drive Linux so didn't notice this one. On Windows the installation contains `chrome.exe` so that makes sense.

Fixed in https://github.com/JAD3N/browsers/commit/41fc44083a870b745442d3da5f3a1105635667b3 and published as v0.1.2.
